In [1]:
import pandas as pd

In [2]:
# define the data as a list
data = [
    ("Dexter","Johnsons","dog","shiba inu","red sesame",1.5,35,"m",False,"both",True),
    ("Alfred","Johnsons","cat","mix","tuxedo",4,12,"m",True,"indoor",True),
    ("Petra","Smith","cat","ragdoll","calico",6,None,"f",False,"both",True),
    ("Ava","Smith","dog","mix","blk/wht",12,32,"f",True,"both",False),
    ("Schroder","Brown","cat","mix","orange",13,15,"m",False,"indoor",True),
    ("Blackbeard","Brown","bird","parrot","multi",5,3,"f",False,"indoor",),
]

# define the labels
labels = ["name","owner","type","breed","color","age","weight","gender","health issues","indoor/outboor","vaccinated"]

# create dataframe
vet_records = pd.DataFrame.from_records(data, columns=labels)

In [3]:
 # displays the first five rows in the dataframe
vet_records.head()

,name,owner,type,breed,color,age,weight,gender,health issues,indoor/outboor,vaccinated
0,Dexter,Johnsons,dog,shiba inu,red sesame,1.5,35.0,m,False,both,True
1,Alfred,Johnsons,cat,mix,tuxedo,4.0,12.0,m,True,indoor,True
2,Petra,Smith,cat,ragdoll,calico,6.0,NaN,f,False,both,True
3,Ava,Smith,dog,mix,blk/wht,12.0,32.0,f,True,both,False
4,Schroder,Brown,cat,mix,orange,13.0,15.0,m,False,indoor,True

In [4]:
 # displays the first five rows in the dataframe
vet_records.tail()

,name,owner,type,breed,color,age,weight,gender,health issues,indoor/outboor,vaccinated
1,Alfred,Johnsons,cat,mix,tuxedo,4.0,12.0,m,True,indoor,True
2,Petra,Smith,cat,ragdoll,calico,6.0,NaN,f,False,both,True
3,Ava,Smith,dog,mix,blk/wht,12.0,32.0,f,True,both,False
4,Schroder,Brown,cat,mix,orange,13.0,15.0,m,False,indoor,True
5,Blackbeard,Brown,bird,parrot,multi,5.0,3.0,f,False,indoor,None

In [5]:
# displays all the records of the datframe
vet_records

,name,owner,type,breed,color,age,weight,gender,health issues,indoor/outboor,vaccinated
0,Dexter,Johnsons,dog,shiba inu,red sesame,1.5,35.0,m,False,both,True
1,Alfred,Johnsons,cat,mix,tuxedo,4.0,12.0,m,True,indoor,True
2,Petra,Smith,cat,ragdoll,calico,6.0,NaN,f,False,both,True
3,Ava,Smith,dog,mix,blk/wht,12.0,32.0,f,True,both,False
4,Schroder,Brown,cat,mix,orange,13.0,15.0,m,False,indoor,True
5,Blackbeard,Brown,bird,parrot,multi,5.0,3.0,f,False,indoor,None

In [6]:
# object means a mixed type column
vet_records.dtypes

name               object
owner              object
type               object
breed              object
color              object
age               float64
weight            float64
gender             object
health issues        bool
indoor/outboor     object
vaccinated         object
dtype: object